--q1. What is the total revenue generated by male vs female customers?

select gender, sum(purchaseamount) as total_revenue
from customer
group by gender

--q2. Which customers used a discount but still spent more than the average purchase amount?
select customerid, purchaseamount from customer
where discountapplied = 'Yes' and purchaseamount >= (select AVG(purchaseamount) from customer)

--q3 which are the top 5 products with the average review rating?
select itempurchased, round(avg(reviewrating)::numeric,2) as avg_reviewrating
from customer
group by itempurchased
order by avg_reviewrating DESC
limit 6


--q4. Compare the average purchase amount between standard and express shipping
select shippingtype, round(avg(purchaseamount)::numeric, 2) as avg_purchasedamount
from customer
where shippingtype in ('Standard', 'Express')
group by shippingtype

--q5.DO subcribed customer spend more? Come average spend and total revenue between
--subscribers and non-subscribers?

select subscriptionstatus,count(customerid) as total_customers, round(AVG(purchaseamount)::numeric, 2) as avepa, 
sum(purchaseamount) as totalrevenue
from customer
group by subscriptionstatus
order by totalrevenue, avepa

--q6. WHich 5 products have the highest percentage of purchases with discount applied?
select itempurchased, 
Round(100 * sum(case when discountapplied='Yes' Then 1 else 0 end)/ count(*), 2) as discount_rate
from customer
group by itempurchased
order by discount_rate desc
limit 5

--q7. Segment customer into new, returning, and loyal based on their total 
--number of previous purchases and show the count of each segment

with customer_type as (
	select customerid, previouspurchases, 
	case when previouspurchases= 1 then 'New'
	when previouspurchases between 2 and 10 Then 'Returning'
	else 'Loyal'
	end
	as customer_segment
from customer
)

select customer_segment, count (*) as numberofcustomer
from customer_type
group by customer_segment

--q8.what are the top 3 most purchased products from each category

with item_counts as (
 select category,
 itempurchased,
 count(customerid) as total_orders,
 row_number () over (partition by category order by count(customerid) desc) as itemrank
 from customer
 group by category, itempurchased
)

select itemrank, category, itempurchased
from item_counts
where itemrank <=3

--q9. are cusotmers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscriptionstatus, count(customerid) as repeat_buyers
from customer
where previouspurchases > 5
group by subscriptionstatus

--q10. what is the revenue contribution by age group
select age_group, sum(purchaseamount) as total_revenue
from customer
group by age_group
order by total_revenue desc


